version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: streamlit run app.py
    ports:
      - "8501:8501"
    env_file:
      - .env
    stdin_open: true
    tty: true
